version: '3.8'

services:
  vocab-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Perzistencia databázy
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
      - LITESTAR_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/')"]
      interval: 30s
      timeout: 10s
      retries: 3
